# Generated by Django 2.2.1 on 2019-07-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CallStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
                ('timestamp', models.DateTimeField()),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='calls.Call')),
            ],
        ),
    ]
