# Generated by Django 2.2.1 on 2019-07-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='calls.Call')),
            ],
        ),
    ]
