# Generated by Django 2.2.1 on 2019-07-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_callend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callend',
            options={'ordering': ['call_id']},
        ),
        migrations.AlterModelOptions(
            name='callstart',
            options={'ordering': ['call_id']},
        ),
    ]
